package tools

// Code generated from the Sectors Financial API OpenAPI schema (docs.sectors.app/schema.json).

var sectorsAPIParams = map[string][]string{
	"/v2/broker-activity/{broker_code}/": {"end", "start", "symbol"},
	"/v2/broker-activity/{broker_code}/top/": {"end", "n_brokers", "start"},
	"/v2/broker-summary/{symbol}/": {"broker_code", "end", "start"},
	"/v2/broker-summary/{symbol}/top/": {"cohort", "end", "n_brokers", "origin", "start"},
	"/v2/brokers/": {"cohort", "origin"},
	"/v2/brokers/top/": {"cohort", "date", "metric", "n_brokers", "origin"},
	"/v2/close/": {"date", "limit", "offset"},
	"/v2/companies/": {"desc", "include_query_values", "limit", "offset", "order_by", "q", "where"},
	"/v2/companies/list_companies_with_segments/": {},
	"/v2/companies/quarterly-financial-dates/": {"limit", "offset", "since", "year"},
	"/v2/companies/top-changes/": {"classifications", "min_mcap_billion", "n_stock", "periods", "sub_sector"},
	"/v2/company/corporate-actions/{symbol}/": {},
	"/v2/company/get-segments/{symbol}/": {"financial_year"},
	"/v2/company/get_quarterly_financial_dates/{symbol}/": {},
	"/v2/company/report/": {"sections"},
	"/v2/company/report/{symbol}/": {"sections"},
	"/v2/company/shareholders-composition/{symbol}/": {"year"},
	"/v2/daily/{symbol}/": {"end", "start"},
	"/v2/filings/": {"end", "holder_type", "limit", "offset", "sector", "start", "sub_sector", "symbol", "tags", "transaction_type"},
	"/v2/financials/quarterly/{symbol}/": {"approx", "n_quarters", "report_date"},
	"/v2/foreign-flow/{symbol}/": {"end", "start"},
	"/v2/free-float/": {"industry", "sector", "sub_industry", "sub_sector"},
	"/v2/idx-total/": {"end", "start"},
	"/v2/index-daily/{index_code}/": {"end", "start"},
	"/v2/industries/": {},
	"/v2/klse/companies/": {"sector"},
	"/v2/klse/companies/top/": {"classifications", "min_mcap_million", "n_stock", "sector"},
	"/v2/klse/company/report/": {"sections"},
	"/v2/klse/company/report/{symbol}/": {"sections"},
	"/v2/klse/sectors/": {},
	"/v2/listing-performance/{symbol}/": {},
	"/v2/mining/commodities/": {},
	"/v2/mining/commodities/{commodity_name}/price/": {"end_year", "start_year"},
	"/v2/mining/companies/": {"commodity_type", "company_type", "has_financials", "keyword", "limit", "offset"},
	"/v2/mining/companies/financials/{slug}/": {"year"},
	"/v2/mining/companies/ownership/{slug}/": {},
	"/v2/mining/companies/performance/{slug}/": {"commodity_type", "year"},
	"/v2/mining/companies/{slug}/": {},
	"/v2/mining/contracts/": {"contractor", "mine_owner"},
	"/v2/mining/exports/": {"commodity_type", "limit", "year"},
	"/v2/mining/global-commodity/": {"commodity_type", "country", "limit"},
	"/v2/mining/license-auctions/": {"area_type", "commodity_type", "limit", "min_participants", "offset", "order_by", "participant", "province", "qualified", "status"},
	"/v2/mining/license-auctions/{wiup_code}/": {},
	"/v2/mining/licenses/": {"activity", "cnc", "commodity_type", "company", "expiring_soon", "license_type", "limit", "offset", "order_by", "province"},
	"/v2/mining/resources-reserves/": {},
	"/v2/mining/resources-reserves/{province}/": {"commodity_type", "year"},
	"/v2/mining/sales-destination/{slug}/": {"year"},
	"/v2/mining/sites/": {"commodity_type", "company", "limit", "min_production", "offset", "order_by", "province", "year"},
	"/v2/mining/sites/{slug}/": {},
	"/v2/mining/total-production/": {"commodity_type"},
	"/v2/most-traded/": {"adjusted", "end", "n_stock", "start", "sub_sector"},
	"/v2/news/": {"commodity_type", "end", "extension", "keyword", "limit", "offset", "sector", "start", "sub_sector", "symbols", "tags"},
	"/v2/sgx/buybacks/": {"end", "limit", "offset", "start", "symbol"},
	"/v2/sgx/companies/": {"desc", "include_query_values", "limit", "offset", "order_by", "q", "where"},
	"/v2/sgx/companies/top/": {"classifications", "min_mcap_million", "n_stock", "sector"},
	"/v2/sgx/company/report/": {"sections"},
	"/v2/sgx/company/report/{symbol}/": {"sections"},
	"/v2/sgx/daily/{symbol}/": {"end", "start"},
	"/v2/sgx/filings/": {"end", "holder_type", "limit", "offset", "start", "symbol", "transaction_type"},
	"/v2/sgx/news/": {"end", "limit", "offset", "sector", "start", "sub_sector", "symbols", "tags"},
	"/v2/sgx/sectors/": {},
	"/v2/sgx/short-sell/": {"end", "limit", "offset", "start", "symbol"},
	"/v2/sgx/subsectors/": {},
	"/v2/sgx/tags/": {},
	"/v2/subindustries/": {},
	"/v2/subsector/report/": {"sections"},
	"/v2/subsector/report/{sub_sector}/": {"sections"},
	"/v2/subsectors/": {},
	"/v2/suspensions/": {"end", "limit", "offset", "start", "symbol"},
	"/v2/tags/": {},
}
