package config

import (
	"bufio"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func Path() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return "kerenscope.config"
	}
	return filepath.Join(home, ".kerenscope", "config")
}

func Load() map[string]string {
	out := map[string]string{}
	f, err := os.Open(Path())
	if err != nil {
		return out
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		val := strings.TrimSpace(parts[1])
		if key != "" && val != "" {
			out[key] = val
		}
	}
	return out
}

func Save(values map[string]string) error {
	if err := os.MkdirAll(filepath.Dir(Path()), 0o700); err != nil {
		return err
	}
	merged := Load()
	for k, v := range values {
		merged[k] = v
	}
	f, err := os.OpenFile(Path(), os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600)
	if err != nil {
		return err
	}
	defer f.Close()
	w := bufio.NewWriter(f)
	w.WriteString("# KerenScope configuration — generated by the interactive setup.\n")
	w.WriteString("# Environment variables take precedence over this file.\n")
	keys := make([]string, 0, len(merged))
	for k := range merged {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		w.WriteString(k + "=" + merged[k] + "\n")
	}
	return w.Flush()
}

func Get(key string) (string, bool) {
	v, ok := Load()[key]
	return v, ok && v != ""
}
